### ISSUE TITLE
[Multiple] Allow input for multiple dates

### ISSUE THREAD

**Issue by guillaumegarcia13** [mattlewis92/angularx-flatpickr#8] opened 2017-11-15 11:18 UTC
My input is defined as the following:
```
<input id="date" type="text" class="form-control" 
                                   mwlFlatpickr 
                                   [altInput]="false"
                                   [dateFormat]="'d/m/Y'"
                                   [allowInput]="true"
                                   [maxDate]="'today'"
                                   [mode]="'multiple'"                                   
                                   [(ngModel)]="dates"
                                   [ngClass]="{'has-value': date}"
                                   placeholder="jj/mm/aaaa, ...">
```

I'm having an issue when trying to type a new set of dates (e.g.: "07/11/2017, 09/11/2017, 11/11/2017"), only the first one gets validated.
Worse, if - after having selected multiples dates in the calendar - I press enter in the input, only the first date remains.

Any idea how to solve this behaviour?
Many thanks in advance.

**Comment by mattlewis92** [comment] 2017-11-20 19:27
Sorry I'm not really sure I follow you, please could you make a plunker, stackblitz etc that reproduces your problem. Thanks!

**Comment by jafp2000** [comment] 2017-12-03 20:18
You can use de mode directive for multiple dates
https://mattlewis92.github.io/angularx-flatpickr/docs/directives/FlatpickrDirective.html#mode

**Comment by mattlewis92** [comment] 2017-12-10 15:23
Closing due to lack response, happy to debug more with a repro!

**Closed by mattlewis92** 2017-12-10 15:23 UTC
